In [29]:
# scripts/encode_fasta.py
import sys, numpy as np

map4 = {ord('A'):0, ord('C'):1, ord('G'):2, ord('T'):3, ord('-'):255}

name, seqs = None, []
file_name = "tiny.fa"

for line in open(file_name):
    line = line.strip()
    if not line: continue
    if line.startswith('>'):
        name = line[1:]
    else:
        if name:
            seqs.append(line)
            name = None

N, M = len(seqs), len(seqs[0])
arr = np.empty((N,M), dtype=np.uint8)

for i,s in enumerate(seqs):
    assert len(s)==M
    arr[i,:] = np.frombuffer(s.encode(), dtype=np.uint8)

arr = np.vectorize(lambda b: map4.get(b,255))(arr)
# arr.tofile(sys.argv[2])     # raw binary row-major (N*M bytes)
print(arr)

[[  0   1   2   3   0   1]
 [  0   1   2   3   3   1]
 [  0   1   2 255 255   1]
 [  0   1   2   3   0   0]]


In [1]:
import numpy as np

# adjust N to the number of sequences in your alignment
N = 4   # for the toy example
matrix = np.fromfile("../cpu_dist.bin", dtype=np.float32).reshape((N, N))

print(matrix)


[[0.         0.16666667 0.16666667 0.        ]
 [0.16666667 0.         0.33333334 0.16666667]
 [0.16666667 0.33333334 0.         0.16666667]
 [0.         0.16666667 0.16666667 0.        ]]
